name: Haskell GHC CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'

    - name: Compile
      run: |
        ghc -o Main Main.hs

    - name: Run SAT test
      run: |
        echo -e '1\na || !a\nreturn\nexit' | ./Main

    - name: Run TAUT test
      run: |
        echo -e '2\na || !a\nreturn\nexit' | ./Main

    - name: Run test.txt test
      run: |
        ./Main < test.txt > t.txt

    - name: Run Main_my_stuff
      run: | 
        ./Main_my_stuff < test.txt > t2.txt

    - name: Run compare t and t2 test
      run: | 
        diff t.txt t2.txt
